#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Open Source in Environmental Sustainability  # The title of the book. Will be placed in the left navbar.
author                      : Tobias Augspurger, Eirini Malliaraki and Josh Hopkins  # The author of the book
copyright                   : "2022"  # Copyright year to be placed in the footer
logo                        : ./images/logo.png  # A path to the book logo
description                 : "Preserving stable climate and natural resources with openness"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  timeout: 100
  allow_errors: false

latex:
  latex_engine              : pdflatex  # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
  use_jupyterbook_latex     : true # use sphinx-jupyterbook-latex for pdf builds as default
  latex_documents:
     targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/protontypes/open-source-in-environmental-sustainability  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  base_url: "https://report.opensustain.tech/"
  announcement: "We are looking for more people and organisations to <b><a href=\"https://report.opensustain.tech/index.html#how-to-contribute\" style = \"color: #00e6a7\" >support us</a></b> in this endeavour."
  use_issues_button: true
  use_repository_button: true
  favicon: favicon.png
  extra_footer: |
    <p>
    <a rel="license" href="http://creativecommons.org/licenses/by/3.0/"><img alt="Creative Commons License" style="border-width:0" src="https://licensebuttons.net/l/by/3.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/3.0/">Creative Commons Attribution 3.0 Unported License</a>.
    </p>

sphinx:
  extra_extensions:
  - sphinxext.opengraph
  config:
    ogp_site_url: "https://report.opensustain.tech/"
    ogp_image: "https://report.opensustain.tech/_images/mycelium_sustainability.png"
    ogp_description_length: 58
    ogp_enable_meta_description: true
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    html_show_copyright: false
    execution_show_tb: true
